version: "3"
services:
  db:
    image: "mongo:4.1.13"
  front:
    build: ./src/front
    restart: always
    ports:
      - "8080:8080"
    environment:
      - REACT_APP_REST_API_URL=http://localhost:8081
    depends_on:
      - api
  api:
    build: ./src/api
    restart: always
    ports:
      - "8081:8080"
    environment:
      - MONGODB_URI=mongodb://db/catmash
    depends_on:
      - db
